title = "Ramzy Al-Amine"
# baseURL = "https://ramzyalamine.com"
theme = "hugo-researcher-ramz53"
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "UA-172041562-1"  # add your tracking id

[params]
  author = "Ramzy Al-Amine"
  description = "A professional CV for the web."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Ramzy Al Amine"
    url = "https://github.com/alamine53"
  [params.style]  # appearance options (can be omitted)
    pageWidth = "600px"
    avatarSize = "140px"
    colorBlack = "#23282b"
    colorURLs = "#FF8243"
    colorRed = "#FF8243"
    colorBlue = "#1c39bb" 
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/ramz-53"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:mail@example.com"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://linkedin.com/ralamine"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/alamine53"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/#publications"
    weight = 2
  [[menu.main]]
    name = "Articles"
    url = "/#articles"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 4



[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[taxonomies]
  category = 'categories'
  tag = 'tags'